// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      // case TargetPlatform.windows:
      // return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAdGSKdb_rJEkJm0mn8DWd2Wmn47yV2MkU",
      authDomain: "doandidong-82796.firebaseapp.com",
      projectId: "doandidong-82796",
      storageBucket: "doandidong-82796.firebasestorage.app",
      messagingSenderId: "905299901665",
      appId: "1:905299901665:web:ebd85b0cbd6c674b588ba0",
      measurementId: "G-B9B1B490PE");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbXkOrUfM0JXZDKviNvZGweFv07gprJSQ',
    appId: '1:905299901665:android:c75827f24542f66d588ba0',
    messagingSenderId: '905299901665',
    projectId: 'doandidong-82796',
    storageBucket: 'doandidong-82796.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv-736K5WbZDhHs8bML_R8o2ITEAN0IaQ',
    appId: '1:905299901665:ios:5838bf3d6a3ea487588ba0',
    messagingSenderId: '905299901665',
    projectId: 'doandidong-82796',
    storageBucket: 'doandidong-82796.firebasestorage.app',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv-736K5WbZDhHs8bML_R8o2ITEAN0IaQ',
    appId: '1:905299901665:ios:5838bf3d6a3ea487588ba0',
    messagingSenderId: '905299901665',
    projectId: 'doandidong-82796',
    storageBucket: 'doandidong-82796.firebasestorage.app',
    iosBundleId: 'com.example.books',
  );

  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyAFDoJfK_M7UYT6EuPQ9JttuuTzW6NjPJw',
  //   appId: '1:46712804564:web:2e2505a719f7c66ac41741',
  //   messagingSenderId: '46712804564',
  //   projectId: 'fir-4-96e5f',
  //   authDomain: 'fir-4-96e5f.firebaseapp.com',
  //   storageBucket: 'fir-4-96e5f.appspot.com',
  //   measurementId: 'G-KTZPYPGPEJ',
  // );
}
